apiVersion: 1
datasources:
  - name: InfluxDB-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    password: ${INFLUXDB_PASS}
    isDefault: true
    editable: true
    basicAuth: true
    jsonData:
      version: Flux
      defaultBucket: telegraf
      organization: teleport
    secureJsonData:
      token: ${INFLUXDB_TOKEN}