apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: loadtest
  labels:
    teleport-role: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      teleport-role: auth
  template:
    metadata:
      labels:
        teleport-role: auth
    spec:
      volumes:
        - name: config
          configMap:
            name: auth-config
        - name: creds
          secret:
            secretName: gcp-creds
        - name: license
          secret:
            secretName: license
        - name: storage
          emptyDir: {}
      containers:
        - name: telegraf
          image: telegraf:1.20.3
          envFrom:
            - secretRef:
                name: influxdb-creds
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
        - name: teleport
          image: quay.io/gravitational/teleport-ent:8.0.0
          args: ["-d", "--insecure"]
          ports:
            - name: diag
              containerPort: 3434
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3434
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3434
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/teleport/
              readOnly: true
            - name: license
              mountPath: /var/lib/teleport/license.pem
              subPath: license.pem
              readOnly: true
            - name: creds
              mountPath: /var/lib/teleport/gcp_creds.json
              subPath: gcp_creds.json
              readOnly: true
            - mountPath: /data
              name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: loadtest
spec:
  ports:
    - name: auth
      port: 3025
      targetPort: 3025
    - name: diag
      port: 3434
      targetPort: 3434
  selector:
    teleport-role: auth
  type: ClusterIP
