apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: loadtest
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      volumes:
        - name: telegraf-config
          configMap:
            name: etcd-telegraf-config
        - name: server-certs
          secret:
            secretName: etcd-server-certs
        - name: client-certs
          secret:
            secretName: etcd-client-certs
      containers:
        - name: telegraf
          image: telegraf:1.20.3
          envFrom:
            - secretRef:
                name: influxdb-creds
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
              readOnly: true
            - name: client-certs
              mountPath: /etc/etcd/certs/
              readOnly: true
        - name: etcd
          image: quay.io/coreos/etcd:v3.3.25
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: server-certs
              mountPath: /etc/etcd/certs/
              readOnly: true
          command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=https://etcd-0.etcd:2380,etcd-1=https://etcd-1.etcd:2380,etcd-2=https://etcd-2.etcd:2380"
              exec etcd \
                --name ${HOSTNAME} \
                --advertise-client-urls https://${HOSTNAME}.etcd:2379 \
                --listen-client-urls https://0.0.0.0:2379 \
                --initial-advertise-peer-urls https://${HOSTNAME}.etcd:2380 \
                --listen-peer-urls https://0.0.0.0:2380 \
                --initial-cluster ${PEERS} \
                --trusted-ca-file=/etc/etcd/certs/ca-cert.pem \
                --cert-file=/etc/etcd/certs/server-cert.pem \
                --key-file=/etc/etcd/certs/server-key.pem \
                --peer-cert-file=/etc/etcd/certs/server-cert.pem \
                --peer-key-file=/etc/etcd/certs/server-key.pem \
                --peer-trusted-ca-file=/etc/etcd/certs/ca-cert.pem \
                --client-cert-auth \
                --peer-client-cert-auth \
                --auto-compaction-retention=1
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: loadtest
  labels:
    app: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd