apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: loadtest
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: teleport-tls
          secret:
            secretName: teleport-tls
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8443
              name: https-grafana
              protocol: TCP
            - containerPort: 8888
              name: health
              protocol: TCP
          volumeMounts:
            - name: teleport-tls
              mountPath: /etc/tls/certs/
              readOnly: true
            - name: grafana-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8888
        - name: grafana
          image: grafana/grafana:8.2.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: grafana-creds
            - secretRef:
                name: influxdb-creds
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yaml
              name: grafana-config
              readOnly: true
              subPath: influxdb-datasource.yaml
            - mountPath: /etc/grafana/provisioning/dashboards/default.yaml
              name: grafana-config
              readOnly: true
              subPath: default.yaml
            - mountPath: /var/lib/grafana/dashboards/health-dashboard.json
              name: grafana-config
              subPath: health-dashboard.json
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-https
  namespace: loadtest
spec:
  type: LoadBalancer
  loadBalancerIP: ${GRAFANA_IP}
  selector:
    app: grafana
  ports:
    - name: web
      protocol: TCP
      port: 8443
      targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: loadtest
spec:
  selector:
    app: grafana
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000

