apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: loadtest
data:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_ORG: teleport
  DOCKER_INFLUXDB_INIT_BUCKET: telegraf
  DOCKER_INFLUXDB_INIT_RETENTION: 1w
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:2.0.9
          name: influxdb
          ports:
            - containerPort: 8086
              name: influxdb
          env:
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-creds
                  key: INFLUXDB_PASS
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-creds
                  key: INFLUXDB_TOKEN
          envFrom:
            - configMapRef:
                name: influxdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: loadtest
spec:
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
