apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: loadtest
  labels:
    teleport-role: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      teleport-role: proxy
  template:
    metadata:
      labels:
        teleport-role: proxy
    spec:
      volumes:
        - name: config
          configMap:
            name: proxy-config
        - name: teleport-tls
          secret:
            secretName: teleport-tls
      containers:
        - name: telegraf
          image: telegraf:1.20.3
          envFrom:
            - secretRef:
                name: influxdb-creds
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
        - name: teleport
          image: quay.io/gravitational/teleport-ent:8.0.0
          args: ["-d", "--insecure"]
          ports:
            - name: diag
              containerPort: 3434
              protocol: TCP
            - name: web
              containerPort: 3080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3434
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3434
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/teleport/
              readOnly: true
            - name: teleport-tls
              mountPath: /etc/teleport-tls/
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: loadtest
  labels:
    teleport-role: proxy
spec:
  type: LoadBalancer  
  loadBalancerIP: ${PROXY_IP}
  ports:
  - name: https
    port: 3080
    targetPort: 3080
    protocol: TCP
  - name: sshproxy
    port: 3023
    targetPort: 3023
    protocol: TCP
  - name: k8s
    port: 3026
    targetPort: 3026
    protocol: TCP
  - name: sshtun
    port: 3024
    targetPort: 3024
    protocol: TCP
  - name: mysql
    port: 3036
    targetPort: 3036
    protocol: TCP
  selector:
    teleport-role: proxy